services:
  db:
    image: postgres:16-alpine
    container_name: soclone_db
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB} -h 127.0.0.1",
        ]
      interval: 3s
      timeout: 3s
      retries: 20

  ollama:
    image: ollama/ollama:latest
    container_name: soclone_ollama
    ports:
      - "11434:11434"
    environment:
      OLLAMA_HOST: 0.0.0.0
      OLLAMA_KEEP_ALIVE: 5m
    volumes:
      - ollama_data:/root/.ollama
    healthcheck:
      test: ["CMD", "ollama", "list"]
      interval: 10s
      timeout: 5s
      retries: 20
      start_period: 25s

  api:
    build:
      context: ./api
      dockerfile: Dockerfile
    container_name: soclone_api
    environment:
      DATABASE_URL: ${DATABASE_URL}
      PHX_PORT: ${PHX_PORT}
      PHX_SERVER: "true"
      SECRET_KEY_BASE: ${SECRET_KEY_BASE}
      LLM_API_BASE: ${LLM_API_BASE}
      LLM_MODEL: ${LLM_MODEL}
      POSTGRES_USER: ${POSTGRES_USER}
      DB_HOST: db
      DB_PORT: "5432"
      DB_USER: postgres
    ports:
      - "${PHX_PORT}:4000"
    depends_on:
      db:
        condition: service_healthy
      ollama:
        condition: service_started

  web:
    build:
      context: ./web/frontend
      dockerfile: Dockerfile
    container_name: soclone_web
    ports:
      - "${WEB_PORT}:5173"
    depends_on:
      - api
    environment:
      VITE_API_BASE: "http://localhost:${PHX_PORT}"

volumes:
  db_data:
  ollama_data:
